max_obstacle_height: 3.3 # Can be a large number, currently matched to the obstacle range
footprint: [[-0.49, -0.46], [-0.49, 0.46], [0.45, 0.46], [0.59, 0.10], [0.59, -0.10], [0.45, -0.46]]

# NOTE: Espresso is generally parallel to the ground with 3-wheel drive
map_type: costmap
observation_sources: laser_scan_sensor cv_laser_scan
